### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by ralphcibis-thomann** [raphbibus/wirvsvirus_backend#1]
- change client model to lumen-internal user model
- integrate auth via JWT or other api token approach
- make sure App (raphbibus/wirvsvirus) supports authentication
- make sure it's covered by phpunit tests

**Comment by hakobyansen** [comment]
How about Laravel Passport for api authentication ?

**Comment by ralphcibis-thomann** [comment]
Sounds like a plan! This [medium post](https://medium.com/@yomiomotoso/integrating-laravel-passport-in-your-lumen-project-with-example-1c2b8719c30) could help.

Would be awesome if you can help here. We just have to make sure, the app gets support for the new authentication as well. But this would probably be managable ;-)

**Comment by hakobyansen** [comment]
Unfortunately lumen v7 contains some breaking changes, maybe because of [this commit](https://github.com/laravel/lumen-framework/commit/e131f99e9e9514e2d63dc3b527d88dbdc196f867) 

It causes the "artisan" command to be broken:

> Call to undefined method Laravel\Lumen\Application::configurationIsCached() 

I can fix that error easily by creating an anonymous class:

`$app = new class extends Laravel\Lumen\Application  {
    public function configurationIsCached() { return false; }
};`

but according to [Compatibility](https://lumen.laravel.com/docs/7.x#compatibility), it would be a wonky solution to hack things to use Passport with Lumen. 

Have to figure out something else, something that we can rely on, probably JWT authentication with this package
https://github.com/tymondesigns/jwt-auth

**Comment by ralphcibis-thomann** [comment]
issue closed by #2
